# Text classification

## Adding a hardware accelerator

Please go to the menu and add a GPU as follows:

`Edit > Notebook Settings > Hardware accelerator > (GPU)`

Run the following cell to confirm that the GPU is detected.

In [ ]:
import torch

# Confirm that the GPU is detected

assert torch.cuda.is_available()

# Get the GPU device name.
device_name = torch.cuda.get_device_name()
n_gpu = torch.cuda.device_count()
print(f"Found device: {device_name}, n_gpu: {n_gpu}")
device = torch.device("cuda")

Found device: Tesla T4, n_gpu: 1

In [ ]:
import torch
device = torch.device("cpu")

## Installing Hugging Face's Transformers library
We will use Hugging Face's Transformers (https://github.com/huggingface/transformers), an open-source library that provides general-purpose architectures for natural language understanding and generation with a collection of various pretrained models made by the NLP community. This library will allow us to easily use pretrained models like `BERT` and perform experiments on top of them. We can use these models to solve downstream target tasks, such as text classification, question answering, and sequence labeling.

Run the following cell to install Hugging Face's Transformers library and download a sample data file called tweets.csv that contains tweets about airlines along with a negative, neutral, or positive sentiment rating. Note that you will be asked to link with your Google Drive account to download some of these files. If you're concerned about security risks (there have not been any issues in previous semesters), feel free to make a new Google account and use it for this homework!

In [ ]:
!pip install transformers
!pip install -U -q PyDrive
!pip install nlpaug

import os
import pandas as pd, numpy as np
import matplotlib.pyplot as plt
from transformers import *
import zipfile
import random
import nlpaug.augmenter.word as naw


# Set the following to avoid warning message
os.environ["TOKENIZERS_PARALLELISM"] = "false"

# Applying augmentation to all the selected texts
# Since this may take a while, we shall show progressbar using tqdm
from tqdm.auto import tqdm
tqdm.pandas()

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)
print('success!')



# Download helper functions file
helper_file = drive.CreateFile({'id': '16HW-z9Y1tM3gZ_vFpJAuwUDohz91Aac-'})
helper_file.GetContentFile('helpers.py')
print('helper file downloaded! (helpers.py)')


# Download sample file of tweets
data_file = drive.CreateFile({'id': '1iFkLKs6WNoLbttPmpI-3stisQ8QH_iYC'})
data_file.GetContentFile('student_feedback.csv')
print('students feedback comments downloaded! (student_feedback.csv)')


# # Download sample file of tweets
# data_file = drive.CreateFile({'id': '1QcoAmjOYRtsMX7njjQTYooIbJHPc6Ese'})
# data_file.GetContentFile('tweets.csv')
# print('sample tweets downloaded! (tweets.csv)')

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.50.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.30.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (2025.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (4.13.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Requirement already satisfied: nlpaug in /usr/local/lib/python3.11/dist-packages (1.1.11)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.11/dist-packages (from nlpaug) (2.0.2)
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from nlpaug) (2.2.2)
Requirement already satisfied: requests>=2.22.0 in /usr/local/lib/python3.11/dist-packages (from nlpaug) (2.32.3)
Requirement already satisfied: gdown>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from nlpaug) (5.2.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from gdown>=4.0.0->nlpaug) (4.13.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from gdown>=4.0.0->nlpaug) (3.18.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from gdown>=4.0.0->nlpaug) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->nlpaug) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->nlpaug) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->nlpaug) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.22.0->nlpaug) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.22.0->nlpaug) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.22.0->nlpaug) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.22.0->nlpaug) (2025.1.31)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->nlpaug) (1.17.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown>=4.0.0->nlpaug) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown>=4.0.0->nlpaug) (4.13.1)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown>=4.0.0->nlpaug) (1.7.1)
success!
helper file downloaded! (helpers.py)
students feedback comments downloaded! (student_feedback.csv)

The cell below imports some helper functions we wrote to demonstrate the task on the sample tweet dataset.

# Part 1: Data Prep and Model Specifications

Upload your data using the file explorer to the left. We have provided a function below to tokenize and format your data as BERT requires. Make sure that your csv file, titled final_data.csv, has one column "text" and another column "labels" containing integers.

If you run the cell below without modifications, it will run on the tweets.csv example data we have provided. It imports some helper functions we wrote to demonstrate the task on the sample tweet dataset. You should first run all of the following cells with tweets.csv just to see how everything works. Then, once you understand the whole preprocessing / fine-tuning process, change the csv in the below cell to your final_data.csv file, add any extra preprocessing code you wish, and then run the cells again on your own data.

In [ ]:
from helpers import tokenize_and_format, flat_accuracy
import pandas as pd
from sklearn.model_selection import train_test_split

# df = pd.read_csv('final_data.csv')
# df = pd.read_csv('tweets.csv')
df = pd.read_csv('student_feedback.csv',encoding='latin-1')
df = df.dropna(subset=['comment'])
df = df.sample(frac=1).reset_index(drop=True)
df.loc[df['label'] == 3, 'label'] = 0

ImportError: cannot import name 'AdamW' from 'transformers' (/usr/local/lib/python3.11/dist-packages/transformers/__init__.py)

In [ ]:
df.groupby('label').count()

## Augmentation in training set

We use backtranslation augmentation. For each negative comment, we augmented it three times; from English to German to English, from English to Japaness to English, from English to Spanish to English.

In [ ]:
# Splitting
X_train, X_test, y_train, y_test = train_test_split(df[['comment']], df['label'], test_size=0.15, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.175, random_state=42)

In [ ]:
X_train_neg = X_train[y_train == 2]
# X_train_nt = X_train[y_train == 0]

In [ ]:
y_train_neg = y_train[y_train == 2]
# y_train_nt = y_train[y_train == 0]

In [ ]:
train__neg_zh = pd.DataFrame(columns=['comment'])
# train__neg_de = pd.DataFrame(columns=['comment'])
# train__neg_es = pd.DataFrame(columns=['comment'])
# train__nt_zh = pd.DataFrame(columns=['comment'])
# train__nt_de = pd.DataFrame(columns=['comment'])

In [ ]:

# Selecting the back translation augmentation method
# 4) Back translation augmentation
# back_trans_aug = naw.BackTranslationAug(device="cuda")  # If using GPUs
augmenter = naw.BackTranslationAug(from_model_name='Helsinki-NLP/opus-mt-en-zh', to_model_name='Helsinki-NLP/opus-mt-zh-en', device=device)

train__neg_zh['comment'] = X_train_neg.progress_apply(lambda row : augmenter.augment(row["comment"])[0], axis=1)

In [ ]:
print(train__neg_zh['comment'])

In [ ]:
# augmenter = naw.BackTranslationAug(from_model_name='Helsinki-NLP/opus-mt-en-de', to_model_name='Helsinki-NLP/opus-mt-de-en')

# train__neg_de['comment'] = X_train_neg.progress_apply(lambda row : augmenter.augment(row["comment"])[0], axis=1)

In [ ]:
# augmenter = naw.BackTranslationAug(from_model_name='Helsinki-NLP/opus-mt-en-es', to_model_name='Helsinki-NLP/opus-mt-es-en')

# train__neg_es['comment'] = X_train_neg.progress_apply(lambda row : augmenter.augment(row["comment"])[0], axis=1)

config.json:   0%|          | 0.00/1.47k [00:00<?, ?B/s]

loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-en-es/snapshots/5bc4493d463cf000c1f0b50f8d56886a392ed4ab/config.json
Model config MarianConfig {
  "_name_or_path": "Helsinki-NLP/opus-mt-en-es",
  "activation_dropout": 0.0,
  "activation_function": "swish",
  "add_bias_logits": false,
  "add_final_layer_norm": false,
  "architectures": [
    "MarianMTModel"
  ],
  "attention_dropout": 0.0,
  "bad_words_ids": [
    [
      65000
    ]
  ],
  "bos_token_id": 0,
  "classif_dropout": 0.0,
  "classifier_dropout": 0.0,
  "d_model": 512,
  "decoder_attention_heads": 8,
  "decoder_ffn_dim": 2048,
  "decoder_layerdrop": 0.0,
  "decoder_layers": 6,
  "decoder_start_token_id": 65000,
  "decoder_vocab_size": 65001,
  "dropout": 0.1,
  "encoder_attention_heads": 8,
  "encoder_ffn_dim": 2048,
  "encoder_layerdrop": 0.0,
  "encoder_layers": 6,
  "eos_token_id": 0,
  "extra_pos_embeddings": 65001,
  "force_bos_token_to_be_generated": false,
  "forced_eos_token_id": 0,
  "gradient_checkpointing": false,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2"
  },
  "init_std": 0.02,
  "is_encoder_decoder": true,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2
  },
  "max_length": 512,
  "max_position_embeddings": 512,
  "model_type": "marian",
  "normalize_before": false,
  "normalize_embedding": false,
  "num_beams": 4,
  "num_hidden_layers": 6,
  "pad_token_id": 65000,
  "scale_embedding": true,
  "share_encoder_decoder_embeddings": true,
  "static_position_embeddings": true,
  "transformers_version": "4.46.2",
  "use_cache": true,
  "vocab_size": 65001
}

pytorch_model.bin:   0%|          | 0.00/312M [00:00<?, ?B/s]

loading weights file pytorch_model.bin from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-en-es/snapshots/5bc4493d463cf000c1f0b50f8d56886a392ed4ab/pytorch_model.bin
Attempting to create safetensors variant
Generate config GenerationConfig {
  "bad_words_ids": [
    [
      65000
    ]
  ],
  "bos_token_id": 0,
  "decoder_start_token_id": 65000,
  "eos_token_id": 0,
  "forced_eos_token_id": 0,
  "max_length": 512,
  "num_beams": 4,
  "pad_token_id": 65000
}

Attempting to convert .bin model on the fly to safetensors.
All model checkpoint weights were used when initializing MarianMTModel.

All the weights of MarianMTModel were initialized from the model checkpoint at Helsinki-NLP/opus-mt-en-es.
If your task is similar to the task the model of the checkpoint was trained on, you can already use MarianMTModel for predictions without further training.

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

loading configuration file generation_config.json from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-en-es/snapshots/5bc4493d463cf000c1f0b50f8d56886a392ed4ab/generation_config.json
Generate config GenerationConfig {
  "bad_words_ids": [
    [
      65000
    ]
  ],
  "bos_token_id": 0,
  "decoder_start_token_id": 65000,
  "eos_token_id": 0,
  "forced_eos_token_id": 0,
  "max_length": 512,
  "num_beams": 4,
  "pad_token_id": 65000,
  "renormalize_logits": true
}

config.json:   0%|          | 0.00/1.44k [00:00<?, ?B/s]

loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-es-en/snapshots/c96e2c5399ebfae4fc43d9669556b9afa74bb69d/config.json
Model config MarianConfig {
  "_name_or_path": "Helsinki-NLP/opus-mt-es-en",
  "activation_dropout": 0.0,
  "activation_function": "swish",
  "add_bias_logits": false,
  "add_final_layer_norm": false,
  "architectures": [
    "MarianMTModel"
  ],
  "attention_dropout": 0.0,
  "bad_words_ids": [
    [
      65000
    ]
  ],
  "bos_token_id": 0,
  "classif_dropout": 0.0,
  "classifier_dropout": 0.0,
  "d_model": 512,
  "decoder_attention_heads": 8,
  "decoder_ffn_dim": 2048,
  "decoder_layerdrop": 0.0,
  "decoder_layers": 6,
  "decoder_start_token_id": 65000,
  "decoder_vocab_size": 65001,
  "dropout": 0.1,
  "encoder_attention_heads": 8,
  "encoder_ffn_dim": 2048,
  "encoder_layerdrop": 0.0,
  "encoder_layers": 6,
  "eos_token_id": 0,
  "extra_pos_embeddings": 65001,
  "force_bos_token_to_be_generated": false,
  "forced_eos_token_id": 0,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2"
  },
  "init_std": 0.02,
  "is_encoder_decoder": true,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2
  },
  "max_length": 512,
  "max_position_embeddings": 512,
  "model_type": "marian",
  "normalize_before": false,
  "normalize_embedding": false,
  "num_beams": 4,
  "num_hidden_layers": 6,
  "pad_token_id": 65000,
  "scale_embedding": true,
  "share_encoder_decoder_embeddings": true,
  "static_position_embeddings": true,
  "transformers_version": "4.46.2",
  "use_cache": true,
  "vocab_size": 65001
}

pytorch_model.bin:   0%|          | 0.00/312M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/312M [00:00<?, ?B/s]

loading weights file pytorch_model.bin from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-es-en/snapshots/c96e2c5399ebfae4fc43d9669556b9afa74bb69d/pytorch_model.bin
Attempting to create safetensors variant
Attempting to convert .bin model on the fly to safetensors.
Generate config GenerationConfig {
  "bad_words_ids": [
    [
      65000
    ]
  ],
  "bos_token_id": 0,
  "decoder_start_token_id": 65000,
  "eos_token_id": 0,
  "forced_eos_token_id": 0,
  "max_length": 512,
  "num_beams": 4,
  "pad_token_id": 65000
}

All model checkpoint weights were used when initializing MarianMTModel.

All the weights of MarianMTModel were initialized from the model checkpoint at Helsinki-NLP/opus-mt-es-en.
If your task is similar to the task the model of the checkpoint was trained on, you can already use MarianMTModel for predictions without further training.

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

loading configuration file generation_config.json from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-es-en/snapshots/c96e2c5399ebfae4fc43d9669556b9afa74bb69d/generation_config.json
Generate config GenerationConfig {
  "bad_words_ids": [
    [
      65000
    ]
  ],
  "bos_token_id": 0,
  "decoder_start_token_id": 65000,
  "eos_token_id": 0,
  "forced_eos_token_id": 0,
  "max_length": 512,
  "num_beams": 4,
  "pad_token_id": 65000,
  "renormalize_logits": true
}

tokenizer_config.json:   0%|          | 0.00/44.0 [00:00<?, ?B/s]

loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-en-es/snapshots/5bc4493d463cf000c1f0b50f8d56886a392ed4ab/config.json
Model config MarianConfig {
  "_name_or_path": "Helsinki-NLP/opus-mt-en-es",
  "activation_dropout": 0.0,
  "activation_function": "swish",
  "add_bias_logits": false,
  "add_final_layer_norm": false,
  "architectures": [
    "MarianMTModel"
  ],
  "attention_dropout": 0.0,
  "bad_words_ids": [
    [
      65000
    ]
  ],
  "bos_token_id": 0,
  "classif_dropout": 0.0,
  "classifier_dropout": 0.0,
  "d_model": 512,
  "decoder_attention_heads": 8,
  "decoder_ffn_dim": 2048,
  "decoder_layerdrop": 0.0,
  "decoder_layers": 6,
  "decoder_start_token_id": 65000,
  "decoder_vocab_size": 65001,
  "dropout": 0.1,
  "encoder_attention_heads": 8,
  "encoder_ffn_dim": 2048,
  "encoder_layerdrop": 0.0,
  "encoder_layers": 6,
  "eos_token_id": 0,
  "extra_pos_embeddings": 65001,
  "force_bos_token_to_be_generated": false,
  "forced_eos_token_id": 0,
  "gradient_checkpointing": false,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2"
  },
  "init_std": 0.02,
  "is_encoder_decoder": true,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2
  },
  "max_length": 512,
  "max_position_embeddings": 512,
  "model_type": "marian",
  "normalize_before": false,
  "normalize_embedding": false,
  "num_beams": 4,
  "num_hidden_layers": 6,
  "pad_token_id": 65000,
  "scale_embedding": true,
  "share_encoder_decoder_embeddings": true,
  "static_position_embeddings": true,
  "transformers_version": "4.46.2",
  "use_cache": true,
  "vocab_size": 65001
}

source.spm:   0%|          | 0.00/802k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/826k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.59M [00:00<?, ?B/s]

loading file source.spm from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-en-es/snapshots/5bc4493d463cf000c1f0b50f8d56886a392ed4ab/source.spm
loading file target.spm from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-en-es/snapshots/5bc4493d463cf000c1f0b50f8d56886a392ed4ab/target.spm
loading file vocab.json from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-en-es/snapshots/5bc4493d463cf000c1f0b50f8d56886a392ed4ab/vocab.json
loading file target_vocab.json from cache at None
loading file tokenizer_config.json from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-en-es/snapshots/5bc4493d463cf000c1f0b50f8d56886a392ed4ab/tokenizer_config.json
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at None
loading file tokenizer.json from cache at None
loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-en-es/snapshots/5bc4493d463cf000c1f0b50f8d56886a392ed4ab/config.json
Model config MarianConfig {
  "_name_or_path": "Helsinki-NLP/opus-mt-en-es",
  "activation_dropout": 0.0,
  "activation_function": "swish",
  "add_bias_logits": false,
  "add_final_layer_norm": false,
  "architectures": [
    "MarianMTModel"
  ],
  "attention_dropout": 0.0,
  "bad_words_ids": [
    [
      65000
    ]
  ],
  "bos_token_id": 0,
  "classif_dropout": 0.0,
  "classifier_dropout": 0.0,
  "d_model": 512,
  "decoder_attention_heads": 8,
  "decoder_ffn_dim": 2048,
  "decoder_layerdrop": 0.0,
  "decoder_layers": 6,
  "decoder_start_token_id": 65000,
  "decoder_vocab_size": 65001,
  "dropout": 0.1,
  "encoder_attention_heads": 8,
  "encoder_ffn_dim": 2048,
  "encoder_layerdrop": 0.0,
  "encoder_layers": 6,
  "eos_token_id": 0,
  "extra_pos_embeddings": 65001,
  "force_bos_token_to_be_generated": false,
  "forced_eos_token_id": 0,
  "gradient_checkpointing": false,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2"
  },
  "init_std": 0.02,
  "is_encoder_decoder": true,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2
  },
  "max_length": 512,
  "max_position_embeddings": 512,
  "model_type": "marian",
  "normalize_before": false,
  "normalize_embedding": false,
  "num_beams": 4,
  "num_hidden_layers": 6,
  "pad_token_id": 65000,
  "scale_embedding": true,
  "share_encoder_decoder_embeddings": true,
  "static_position_embeddings": true,
  "transformers_version": "4.46.2",
  "use_cache": true,
  "vocab_size": 65001
}

tokenizer_config.json:   0%|          | 0.00/44.0 [00:00<?, ?B/s]

loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-es-en/snapshots/c96e2c5399ebfae4fc43d9669556b9afa74bb69d/config.json
Model config MarianConfig {
  "_name_or_path": "Helsinki-NLP/opus-mt-es-en",
  "activation_dropout": 0.0,
  "activation_function": "swish",
  "add_bias_logits": false,
  "add_final_layer_norm": false,
  "architectures": [
    "MarianMTModel"
  ],
  "attention_dropout": 0.0,
  "bad_words_ids": [
    [
      65000
    ]
  ],
  "bos_token_id": 0,
  "classif_dropout": 0.0,
  "classifier_dropout": 0.0,
  "d_model": 512,
  "decoder_attention_heads": 8,
  "decoder_ffn_dim": 2048,
  "decoder_layerdrop": 0.0,
  "decoder_layers": 6,
  "decoder_start_token_id": 65000,
  "decoder_vocab_size": 65001,
  "dropout": 0.1,
  "encoder_attention_heads": 8,
  "encoder_ffn_dim": 2048,
  "encoder_layerdrop": 0.0,
  "encoder_layers": 6,
  "eos_token_id": 0,
  "extra_pos_embeddings": 65001,
  "force_bos_token_to_be_generated": false,
  "forced_eos_token_id": 0,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2"
  },
  "init_std": 0.02,
  "is_encoder_decoder": true,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2
  },
  "max_length": 512,
  "max_position_embeddings": 512,
  "model_type": "marian",
  "normalize_before": false,
  "normalize_embedding": false,
  "num_beams": 4,
  "num_hidden_layers": 6,
  "pad_token_id": 65000,
  "scale_embedding": true,
  "share_encoder_decoder_embeddings": true,
  "static_position_embeddings": true,
  "transformers_version": "4.46.2",
  "use_cache": true,
  "vocab_size": 65001
}

source.spm:   0%|          | 0.00/826k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/312M [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/802k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.59M [00:00<?, ?B/s]

loading file source.spm from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-es-en/snapshots/c96e2c5399ebfae4fc43d9669556b9afa74bb69d/source.spm
loading file target.spm from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-es-en/snapshots/c96e2c5399ebfae4fc43d9669556b9afa74bb69d/target.spm
loading file vocab.json from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-es-en/snapshots/c96e2c5399ebfae4fc43d9669556b9afa74bb69d/vocab.json
loading file target_vocab.json from cache at None
loading file tokenizer_config.json from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-es-en/snapshots/c96e2c5399ebfae4fc43d9669556b9afa74bb69d/tokenizer_config.json
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at None
loading file tokenizer.json from cache at None
loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-es-en/snapshots/c96e2c5399ebfae4fc43d9669556b9afa74bb69d/config.json
Model config MarianConfig {
  "_name_or_path": "Helsinki-NLP/opus-mt-es-en",
  "activation_dropout": 0.0,
  "activation_function": "swish",
  "add_bias_logits": false,
  "add_final_layer_norm": false,
  "architectures": [
    "MarianMTModel"
  ],
  "attention_dropout": 0.0,
  "bad_words_ids": [
    [
      65000
    ]
  ],
  "bos_token_id": 0,
  "classif_dropout": 0.0,
  "classifier_dropout": 0.0,
  "d_model": 512,
  "decoder_attention_heads": 8,
  "decoder_ffn_dim": 2048,
  "decoder_layerdrop": 0.0,
  "decoder_layers": 6,
  "decoder_start_token_id": 65000,
  "decoder_vocab_size": 65001,
  "dropout": 0.1,
  "encoder_attention_heads": 8,
  "encoder_ffn_dim": 2048,
  "encoder_layerdrop": 0.0,
  "encoder_layers": 6,
  "eos_token_id": 0,
  "extra_pos_embeddings": 65001,
  "force_bos_token_to_be_generated": false,
  "forced_eos_token_id": 0,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2"
  },
  "init_std": 0.02,
  "is_encoder_decoder": true,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2
  },
  "max_length": 512,
  "max_position_embeddings": 512,
  "model_type": "marian",
  "normalize_before": false,
  "normalize_embedding": false,
  "num_beams": 4,
  "num_hidden_layers": 6,
  "pad_token_id": 65000,
  "scale_embedding": true,
  "share_encoder_decoder_embeddings": true,
  "static_position_embeddings": true,
  "transformers_version": "4.46.2",
  "use_cache": true,
  "vocab_size": 65001
}

  0%|          | 0/49 [00:00<?, ?it/s]

In [ ]:
# augmenter = naw.BackTranslationAug(from_model_name='Helsinki-NLP/opus-mt-en-zh', to_model_name='Helsinki-NLP/opus-mt-zh-en')

# train__nt_zh['comment'] = X_train_nt.progress_apply(lambda row : augmenter.augment(row["comment"])[0], axis=1)

  0%|          | 0/55 [00:00<?, ?it/s]

In [ ]:
# augmenter = naw.BackTranslationAug(from_model_name='Helsinki-NLP/opus-mt-en-de', to_model_name='Helsinki-NLP/opus-mt-de-en')

# train__nt_de['comment'] = X_train_nt.progress_apply(lambda row : augmenter.augment(row["comment"])[0], axis=1)

  0%|          | 0/55 [00:00<?, ?it/s]

In [ ]:
# X_train_aug = pd.concat([X_train, train__neg_zh, train__neg_de, train__neg_es, train__nt_zh, train__nt_de], axis=0, ignore_index=True)
X_train_aug = pd.concat([X_train, train__neg_zh], axis=0, ignore_index=True)

In [ ]:
# y_train_aug = pd.concat([y_train, y_train_neg, y_train_neg, y_train_neg, y_train_nt, y_train_nt], axis=0, ignore_index=True)
y_train_aug = pd.concat([y_train, y_train_neg], axis=0, ignore_index=True)

In [ ]:
y_train_aug.groupby(y_train_aug).count()

label
0    109
1    101
2    108
Name: label, dtype: int64

In [ ]:
train_aug = pd.concat([X_train_aug, y_train_aug], axis=1)
# Shuffle the DataFrame rows
train_aug_shuffled = train_aug.sample(frac=1, random_state=42)

# Extract the shuffled Series
X_train = train_aug_shuffled['comment']
y_train = train_aug_shuffled['label']

In [ ]:
num_train = X_train.shape[0]
num_val = X_val.shape[0]
num_test = X_test.shape[0]
total = num_train + num_val + num_test

In [ ]:
print("Train set:", X_train.shape, y_train.shape)
print("Validation set:", X_val.shape, y_val.shape)
print("Test set:", X_test.shape, y_test.shape)

Train set: (318,) (318,)
Validation set: (56, 1) (56,)
Test set: (57, 1) (57,)

In [ ]:
X = pd.concat([X_train, X_val, X_test], axis=0)
y = pd.concat([y_train, y_val, y_test], axis=0)
texts = X.comment.values
labels = y.values

In [ ]:
y.groupby(y).count()

label
0    152
1    147
2    132
Name: label, dtype: int64

In [ ]:
# texts = df.comment.values
# # texts = df.text.values
# # df.label[df.label == 'O'] = 1
# # df.label[df.label == 'N'] = 0
# df.label[df.label == 3] = 0
# df.label = df.label.astype('int64')
# labels = df.label.values

In [ ]:
texts.shape

(431,)

In [ ]:
labels.shape

(431,)

## Create train/test/validation splits

Here we split your dataset into 3 parts: a training set, a validation set, and a testing set. Each item in your dataset will be a 3-tuple containing an input_id tensor, an attention_mask tensor, and a label tensor.

In [ ]:
### tokenize_and_format() is a helper function provided in helpers.py ###
input_ids, attention_masks = tokenize_and_format(texts)

# Convert the lists into tensors.
input_ids = torch.cat(input_ids, dim=0)
attention_masks = torch.cat(attention_masks, dim=0)
labels = torch.tensor(labels)

# Print sentence 0, now as a list of IDs.
print('Original: ', texts[0])
print('Token IDs:', input_ids[0])

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

loading file vocab.txt from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/86b5e0934494bd15c9632b12f734a8a67f723594/vocab.txt
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at None
loading file tokenizer_config.json from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/86b5e0934494bd15c9632b12f734a8a67f723594/tokenizer_config.json
loading file tokenizer.json from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/86b5e0934494bd15c9632b12f734a8a67f723594/tokenizer.json

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/86b5e0934494bd15c9632b12f734a8a67f723594/config.json
Model config BertConfig {
  "_name_or_path": "bert-base-uncased",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.46.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Original:  Virtual Classes and questions that was given by Professor.
Token IDs: tensor([ 101, 7484, 4280, 1998, 3980, 2008, 2001, 2445, 2011, 2934, 1012,  102,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0])

In [ ]:
train_set = [(input_ids[i], attention_masks[i], labels[i]) for i in range(num_train)]
train_text = [texts[i] for i in range(num_train)]

val_set = [(input_ids[i], attention_masks[i], labels[i]) for i in range(num_train, num_val+ num_train)]
test_set = [(input_ids[i], attention_masks[i], labels[i]) for i in range(num_val + num_train, total)]

val_text = [texts[i] for i in range(num_train, num_val+num_train)]
test_text = [texts[i] for i in range(num_val + num_train, total)]

Here we choose the model we want to finetune from https://huggingface.co/transformers/pretrained_models.html. Because the task requires us to label sentences, we wil be using BertForSequenceClassification below. You may see a warning that states that `some weights of the model checkpoint at [model name] were not used when initializing. . .` This warning is expected and means that you should fine-tune your pre-trained model before using it on your downstream task. See [here](https://github.com/huggingface/transformers/issues/5421#issuecomment-652582854) for more info.

In [ ]:
from transformers import BertForSequenceClassification, AdamW, BertConfig

model = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased", # Use the 12-layer BERT model, with an uncased vocab.
    num_labels = 3, # The number of output labels.
    output_attentions = False, # Whether the model returns attentions weights.
    output_hidden_states = False, # Whether the model returns all hidden-states.
)

# Tell pytorch to run this model on the GPU.
model.cuda()

loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/86b5e0934494bd15c9632b12f734a8a67f723594/config.json
Model config BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.46.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weights file model.safetensors from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/86b5e0934494bd15c9632b12f734a8a67f723594/model.safetensors
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=3, bias=True)
)

# ACTION REQUIRED #

Define your fine-tuning hyperparameters in the cell below (we have randomly picked some values to start with). We want you to experiment with different configurations to find the one that works best (i.e., highest accuracy) on your validation set. Feel free to also change pretrained models to others available in the HuggingFace library (you'll have to modify the cell above to do this). You might find papers on BERT fine-tuning stability (e.g., [Mosbach et al., ICLR 2021](https://openreview.net/pdf?id=nzpLWnVAyah)) to be of interest.

In [ ]:
batch_size = 32
optimizer = AdamW(model.parameters(),
                  lr = 5e-6, # args.learning_rate - default is 5e-5
                  eps = 1e-8 # args.adam_epsilon  - default is 1e-8
                )
epochs = 30

# Fine-tune your model
Here we provide code for fine-tuning your model, monitoring the loss, and checking your validation accuracy. Rerun both of the below cells when you change your hyperparameters above.

In [ ]:
import numpy as np
# function to get validation accuracy
def get_validation_performance(val_set):
    # Put the model in evaluation mode
    model.eval()

    # Tracking variables
    total_eval_accuracy = 0
    total_eval_loss = 0

    num_batches = int(len(val_set)/batch_size) + 1

    total_correct = 0

    for i in range(num_batches):

      end_index = min(batch_size * (i+1), len(val_set))

      batch = val_set[i*batch_size:end_index]

      if len(batch) == 0: continue

      input_id_tensors = torch.stack([data[0] for data in batch])
      input_mask_tensors = torch.stack([data[1] for data in batch])
      label_tensors = torch.stack([data[2] for data in batch])

      # Move tensors to the GPU
      b_input_ids = input_id_tensors.to(device)
      b_input_mask = input_mask_tensors.to(device)
      b_labels = label_tensors.to(device)

      # Tell pytorch not to bother with constructing the compute graph during
      # the forward pass, since this is only needed for backprop (training).
      with torch.no_grad():

        # Forward pass, calculate logit predictions.
        outputs = model(b_input_ids,
                                token_type_ids=None,
                                attention_mask=b_input_mask,
                                labels=b_labels)
        loss = outputs.loss
        logits = outputs.logits

        # Accumulate the validation loss.
        total_eval_loss += loss.item()

        # Move logits and labels to CPU
        logits = logits.detach().cpu().numpy()
        label_ids = b_labels.to('cpu').numpy()

        # Calculate the number of correctly labeled examples in batch
        pred_flat = np.argmax(logits, axis=1).flatten()
        labels_flat = label_ids.flatten()
        num_correct = np.sum(pred_flat == labels_flat)
        total_correct += num_correct

    # Report the final accuracy for this validation run.
    avg_val_accuracy = total_correct / len(val_set)
    return avg_val_accuracy

In [ ]:
import random

# training loop

# For each epoch...
for epoch_i in range(0, epochs):
    # Perform one full pass over the training set.

    print("")
    print('======== Epoch {:} / {:} ========'.format(epoch_i + 1, epochs))
    print('Training...')

    # Reset the total loss for this epoch.
    total_train_loss = 0

    # Put the model into training mode.
    model.train()

    # For each batch of training data...
    num_batches = int(len(train_set)/batch_size) + 1

    for i in range(num_batches):
      end_index = min(batch_size * (i+1), len(train_set))

      batch = train_set[i*batch_size:end_index]

      if len(batch) == 0: continue

      input_id_tensors = torch.stack([data[0] for data in batch])
      input_mask_tensors = torch.stack([data[1] for data in batch])
      label_tensors = torch.stack([data[2] for data in batch])

      # Move tensors to the GPU
      b_input_ids = input_id_tensors.to(device)
      b_input_mask = input_mask_tensors.to(device)
      b_labels = label_tensors.to(device)

      # Clear the previously calculated gradient
      model.zero_grad()

      # Perform a forward pass (evaluate the model on this training batch).
      outputs = model(b_input_ids,
                            token_type_ids=None,
                            attention_mask=b_input_mask,
                            labels=b_labels)
      loss = outputs.loss
      logits = outputs.logits

      total_train_loss += loss.item()

      # Perform a backward pass to calculate the gradients.
      loss.backward()

      # Update parameters and take a step using the computed gradient.
      optimizer.step()

    # ========================================
    #               Validation
    # ========================================
    # After the completion of each training epoch, measure our performance on
    # our validation set. Implement this function in the cell above.
    print(f"Total loss: {total_train_loss}")
    val_acc = get_validation_performance(val_set)
    print(f"Validation accuracy: {val_acc}")

print("")
print("Training complete!")

======== Epoch 1 / 30 ========
Training...
Total loss: 11.353326201438904
Validation accuracy: 0.23214285714285715

======== Epoch 2 / 30 ========
Training...
Total loss: 10.762079000473022
Validation accuracy: 0.32142857142857145

======== Epoch 3 / 30 ========
Training...
Total loss: 10.277157187461853
Validation accuracy: 0.48214285714285715

======== Epoch 4 / 30 ========
Training...
Total loss: 9.750039100646973
Validation accuracy: 0.5892857142857143

======== Epoch 5 / 30 ========
Training...
Total loss: 9.398296058177948
Validation accuracy: 0.6607142857142857

======== Epoch 6 / 30 ========
Training...
Total loss: 8.795197427272797
Validation accuracy: 0.6964285714285714

======== Epoch 7 / 30 ========
Training...
Total loss: 8.225375652313232
Validation accuracy: 0.75

======== Epoch 8 / 30 ========
Training...
Total loss: 7.723346531391144
Validation accuracy: 0.75

======== Epoch 9 / 30 ========
Training...
Total loss: 7.23771071434021
Validation accuracy: 0.7678571428571429

======== Epoch 10 / 30 ========
Training...
Total loss: 6.696470379829407
Validation accuracy: 0.7857142857142857

======== Epoch 11 / 30 ========
Training...
Total loss: 6.067425072193146
Validation accuracy: 0.8035714285714286

======== Epoch 12 / 30 ========
Training...
Total loss: 5.722119987010956
Validation accuracy: 0.7857142857142857

======== Epoch 13 / 30 ========
Training...
Total loss: 5.240136235952377
Validation accuracy: 0.7857142857142857

======== Epoch 14 / 30 ========
Training...
Total loss: 4.88489294052124
Validation accuracy: 0.8035714285714286

======== Epoch 15 / 30 ========
Training...
Total loss: 4.345105290412903
Validation accuracy: 0.7857142857142857

======== Epoch 16 / 30 ========
Training...
Total loss: 4.065669596195221
Validation accuracy: 0.7857142857142857

======== Epoch 17 / 30 ========
Training...
Total loss: 3.7371301352977753
Validation accuracy: 0.8035714285714286

======== Epoch 18 / 30 ========
Training...
Total loss: 3.513713389635086
Validation accuracy: 0.8035714285714286

======== Epoch 19 / 30 ========
Training...
Total loss: 3.096237376332283
Validation accuracy: 0.7857142857142857

======== Epoch 20 / 30 ========
Training...
Total loss: 2.7834116369485855
Validation accuracy: 0.7857142857142857

======== Epoch 21 / 30 ========
Training...
Total loss: 2.5406283289194107
Validation accuracy: 0.7857142857142857

======== Epoch 22 / 30 ========
Training...
Total loss: 2.1995614022016525
Validation accuracy: 0.7857142857142857

======== Epoch 23 / 30 ========
Training...
Total loss: 1.9836766123771667
Validation accuracy: 0.75

======== Epoch 24 / 30 ========
Training...
Total loss: 1.867817297577858
Validation accuracy: 0.7678571428571429

======== Epoch 25 / 30 ========
Training...
Total loss: 1.6529370248317719
Validation accuracy: 0.7857142857142857

======== Epoch 26 / 30 ========
Training...
Total loss: 1.463867425918579
Validation accuracy: 0.75

======== Epoch 27 / 30 ========
Training...
Total loss: 1.300670325756073
Validation accuracy: 0.7857142857142857

======== Epoch 28 / 30 ========
Training...
Total loss: 1.188367947936058
Validation accuracy: 0.7857142857142857

======== Epoch 29 / 30 ========
Training...
Total loss: 1.0003388747572899
Validation accuracy: 0.7678571428571429

======== Epoch 30 / 30 ========
Training...
Total loss: 0.96268031001091
Validation accuracy: 0.7678571428571429

Training complete!

# Evaluate your model on the test set
After you're satisfied with your hyperparameters (i.e., you're unable to achieve higher validation accuracy by modifying them further), it's time to evaluate your model on the test set! Run the below cell to compute test set accuracy.

In [ ]:
get_validation_performance(test_set)

0.8947368421052632

In [ ]:
def error_analysis(tensor_set, text_set):
    model.eval()
    batch = tensor_set

    input_id_tensors = torch.stack([data[0] for data in batch])
    input_mask_tensors = torch.stack([data[1] for data in batch])
    label_tensors = torch.stack([data[2] for data in batch])

    # Move tensors to the GPU
    b_input_ids = input_id_tensors.to(device)
    b_input_mask = input_mask_tensors.to(device)
    b_labels = label_tensors.to(device)

    # Tell pytorch not to bother with constructing the compute graph during
    # the forward pass, since this is only needed for backprop (training).
    with torch.no_grad():

        # Forward pass, calculate logit predictions.
        outputs = model(b_input_ids,
                                token_type_ids=None,
                                attention_mask=b_input_mask,
                                labels=b_labels)

        logits = outputs.logits
        logits = logits.detach().cpu().numpy()
        label_ids = b_labels.to('cpu').numpy()

        # Calculate the number of correctly labeled examples in batch
        pred_flat = np.argmax(logits, axis=1).flatten()
        labels_flat = label_ids.flatten()

        for i in range(labels_flat.size):
          if pred_flat[i] != labels_flat[i]:
            print("Incorrect -- " + text_set[i])
          else:
            print("Correct -- " + text_set[i])

In [ ]:

error_analysis(val_set, val_text)

Correct -- I liked that this class was very discussion–based. I also liked how the professor went through practice problems for the energy
portion of the course.
Incorrect -- nothing
Incorrect -- How the activities aided the content we were learning
Correct -- allow for more in class interaction and open yourself up for more questions during lectures
Correct -- It was good
Correct -- Overall it was a good course, and that’s coming from someone who has absolutely no interest in LEED.
Correct -- The way instructor teaching us this course makes more interest to gain knowledge and also to participate in activities in class and
 many more. So, I like every aspects of this course.
Incorrect -- Be prepared for a lot of homework, which is a repeat of the materials class we took sophomore year. Also, the lab reports are very
unclear, and require a lot of time and effort.
Incorrect -- she is friendly – fast response – but sometimes so tough
Correct -- Take this subject, it would help in better understanding of sustainability and related concepts.
Correct -- I learned a tremendous lot, due to the presentation of the material and due to the amount of practice.
Incorrect -- TO improve this course the first step is to shorten the class time. We were originally given two almost 3 hour long class periods
Correct -- Stays always in touch.
Correct -- Study and take good notes, make sure you understand how to do the problems, but also why you are doing the problems. It will make
the class much easier and you will get more out of it.
Correct -- Absolutely take it. Definitely made my life easier.
Incorrect -- If you are going to assign a similar project next semester then touch on beam, girder and column placements earlier in the semester.
Incorrect -- I would change the grading breakdown. Class participation and attendance should count, and homework should count more than it
does.
Incorrect -- The exam questions didn't resemble what we practiced in class. Yes, they included some many of the same topics. But students
were expected to pull together different ideas in a way that they were not necessarily prepared or shown how to do.
Correct -- The advice I would give to another student would be to work on group projects early. There was an overlap on projects in the class
and a lot was required of the students at that time.
Incorrect -- No suggestions.
Correct -- Class story and class discussion
Correct -- The instructor's through explanation of the course material.
Correct -- Organize workload, there is a lot of work outside of class.
Correct -- Enthusiasm. Simplification of complex topics so I didn’t get lost in the details, but also provided explanations for a deeper
understanding of the concepts.
Correct -- It was good
Correct -- study and do not neglect
Incorrect -- Too much work with lectures, quizzes, homeworks, exams, and labs
Correct -- It was hands on.
Incorrect -- I would suggest showing every step when doing calculations. There were times when the class was confused about how she got
the number on the board because not all steps were shown.
Correct -- she is engaging
Correct -- I enjoyed coming to lecture and learning as much as I could on the subject.
Incorrect -- More in depth lessons. the teacher relies on you to learn yourself alot.
Correct -- Be prepared to spend more time than you thought on this course. It is still worth three credit – same as structural analysis and
hydraulics.
Incorrect -- learn the topics you are teaching before you teach it.

In [ ]:
error_analysis(test_set, test_text)

Incorrect -- Nothing
Correct -- doing more inclass problems
Correct -- Mailing the concrete ingredients was very nice.
Correct -- Always willing to help students.
Incorrect -- Be a little more clear when making plans
Incorrect -- To be honest I don't have any suggestions
Correct -- Interesting
Incorrect -- You will not have a break from this class until the final exam is given.
Incorrect -- The homework although helpful, was a large load at times, especially when compared to other the fundamentals classes. An
example based class is nice but, the lectures were sometimes to brief and to careless. I felt the lectures would confused me
more, while the examples would provide SOME clarity. Much learning was spent by me, teaching myself and seeing the trends
myself. A good class has balance of all things, and just remember your students cant see things or do things as quick as you!
Correct -- I enjoyed my first semester as an engineering student. I believe achieving a high grade in this course is reachable as long as the
student works hard and makes an effort to come to class.
Correct -- Nothing, I am very satisfied with the instructor's teaching.
Correct -- no suggestions needed. Professor is too good in teaching.
Incorrect -- give her atleast one in person session
Correct -- I liked how she had breakout sessions for discussions.
Incorrect -- Focusing more on explaining lecture instead of examples
Correct -- Pay attention because this course covers a lot of content.
Correct -- Very knowledgeable and resourceful if needed help.
Correct -- I enjoyed the hands–on bridge building project the most, during this project I was able to feel confident about my ability to construct
a correct bridge partially due to GN's teaching and guidance.
Incorrect -- Take this course online.
Correct -- gave a lot of information
Incorrect -- A 2 hours class of pure theory is not necessary. This is a lab class. We already took materials, which covered what was taught in this
class during the first part of the semester.
Correct -- have a strong knowledge of structural analysis
Correct -- Study throughout the semester for exams. There is too much content in this course to cram your studying. Professor Nossoni provides
great notes to her students and they should all take advantage of this.
Correct -- As this is more interactive course it’s better to make it on ground instead of online
Correct -- The class with the specific teacher is great and very interesting. Overall even the teacher is willing to work with you if you need to
move a test or not. there flexible and it is truly helpful. I enjoyed the class, just . do . the . homwork
Correct -- I liked how students were given the opportunity to go back and correct their lab reports. Doing that enhanced my learning in the
class, as I re–visited topics I did not fully understand the first time around and was able to see where exactly I went wrong.
Correct -- I enjoyed being able to do the labs while at school.
Incorrect -- make homework worth more points since it is every week and takes a long time to do.
Correct -- She was very into the content she was teaching.
Correct -- Her enthusiasm for the subject matter. Also, the clear steps provided for solving problems.
Correct -- With the power–points on blackboard. Maybe make them filled out on blackbaord for students that may have lost the physical
packet. it'll also allow for review to be easier and faster
Correct -- the consistency of due dates and expectations
Correct -- Helped me apply new skills to real–life problems.
Correct -- Very helpful and enthusiastic about the material being taught.
Incorrect -- pay close attention.

In [ ]:
error_analysis(train_set, train_text)

Correct -- Take really good notes.
Correct -- All of the assignments and modules we had to do were clearly organized on Canvas. My instructor was very approachable and
Incorrect -- My experience was overall difficultly challenging me in this course
Incorrect -- Be more careful while walking down stairs
Correct -- She thought us Many examples to understand the subject.
Correct -- Dr. Nossoni has a high energy that I absolutely love during college. I never feel tired whenever I am in her class and is always
helpful with questions.
Incorrect -- keep up
Correct -- I enjoyed the lectures and how my professor was able to make each class relatable to the real world.
Incorrect -- The course was taught very well. The only thing that made this semester more challenging than usual was the unexpected transition
to online courses. The online exams were extremely difficult, and I imagine in–class exams would be easier to complete in the given
time frame. If this class is online again in the future, I feel like arrangements should be made to account for obstacles like loading
and navigating the online exam. Even giving a few extra minutes per exam to account for these issues would go a long way for
online students.
Correct -- Everything was explained very well, the homework load is more equivalent to the amount its worth for our grade.
Incorrect -- I thought some sections were taught a little too fast, but it wasn't the case for all the sections. Otherwise, I have no critiques, the
class was really good.
Correct -- dont fall behind!
Correct -- I really liked how open the class was. Dr. Nossoni really fostered an environment for open discussion and I enjoyed both listening
and participating during class.
Correct -- Teaching skill along with practical examples
Incorrect -- Less work. Resumes, though easy for the end of the semester are not as beneficial. Students should not be waiting until
December to have a perfectly crafted cover letter and resume. This section could be flipped with ethics.
Sept – Resume and cover letters (2.5 weeks)
Oct – Sustainability (lots of lecture and project time)
Dec – Ethics (Finish up at the end – students will still have easy final)
Incorrect -- No suggestions.
Incorrect -- Good experince, bridge project is horrible
Correct -- I will ask upcoming students to take course for sure.
Incorrect -- Though the weightage of various sections for grading were pretty clear, if the instructor would have been more flexible understanding
the current situation, students' overall grades would be much better.
Incorrect -- More oppurtunitites for extra help/ credit
Correct -- study well – prepare for the exam – do your homework on time – focus in class time
Incorrect -- Having the homework with the same difficulty as exams.
Incorrect -- nones
Correct -- It was good
Correct -- reach out to her for help when you need it
Correct -- My advice to another student is to participate whenever you get a chance. The class is more fun when students are conversing with
the professor and vice versa, not only when the professor speaks. The class covers many topics so you will definitely have an opinion
or idea on to something. Don't be afraid to share!
Correct -- it was good
Correct -- I took a very similar course in high and it was much more loosely taught which was much more enjoyable.
Correct -- Include more basic examples on the worksheets and explain why things are happening more.
Incorrect -- It was rough, not a good time. In the words of the great Ariana Grande, "Thank you, next."
Correct -- Overall, the course was great! I truly feel that I have a good grasp on concrete design after taking this course.
Incorrect -- Lower the class size or bigger room, my neck hurts.
Incorrect -- The number of practice problems that were performed in class.
Correct -- Every student has to take this course which gives more information and also this course is more important for civil engineers. So, I
advice other students to register this course.
Incorrect -- Design Advance Reinforced concrete
Correct -- There are many things that I like it about this class, but what i really like it the most was that Dr. Nossoni was always well prepared
for every class and her way of explaining the example problems were the best.
Incorrect -- go a little slower
Incorrect -- Nothing
Correct -- I liked how she was strict with us. It made the class difficult but i understood the topics much more.
Correct -- Class notes and PP.
Incorrect -- The instructor could be very demanding of the students at times. This cauesd the class time because people have jobs and other
things to take care of.
Incorrect -- I believe that the problems in the exams were a lot more complex than anything we had previously seen in either class problems or
homework problems. I don't believe that this fair because the weight of the exams is so much more than the homework. Why give us
even harder problems in an exam, not giving us an opportunity to properly prepare for these type of problems. Also, most of the work
we do for the class is homework problems, how is fair that it is only worth 5% of the final grade.
Correct -- I enjoyed watching videos to see geological events in action.
Correct -- I like how straight forward the information was. The instructor made the material easy and understandable.
Correct -- Try to learn some of the basics such as Arduino before starting the class to make it easier to learn.
Correct -- Practice. Professor takes us to the career fair and practices what we learned in class.
Incorrect -- If given online with students being home again, ease the coursework, some students may have obligations at home before school
work, did not help the situation given from COVID–19, left students stressed on top of the very stressful pandemic.
Correct -- I liked how there was a printout for each topic that was covered in class containing examples that were done on our own, then
completed as a class.
Incorrect -- No Suggestions.
Correct -- take this course ,it helps you to improve your skills
Correct -- Dr. Nossoni is absolutely amazing. I would have never wanted a better professor for this class. The way she teaches is very helpful
for learning how to do truss, forces, and stress/strain analysis. I feel like I have learned so much from this class.
Incorrect -- none
Incorrect -- maybe more examples in the lecture, besides that everything is ok
Incorrect -- be ready to make more efforts compare to other subjects
Incorrect -- My learning experience in this class was hindered by the atmosphere generated by the teacher. at times I did not look forward to going
to class due because of this atmosphere. This is something that has never happened in my college career. The class was hard and
demanding which I expected and had no problem with. However I felt that this atmosphere added another level of difficulty and did not
make for a good learning experience.
Incorrect -- more feedback when grading and more information on how the exams and quizzes will be graded. course was extremely hard to
learn online and became very difficult when online classes started. definitely should not be taught online also more partial credit
Incorrect -- too much work
Correct -- All
Correct -- I liked being able to work in groups for most of the class
Correct -- I learned well throughout the class and my previous knowledge had contributed to my understanding of the class.
Correct -- the enthusiasm
Incorrect -- none
Incorrect -- Pick a good team for the lab reports.
Correct -- she has a steep by steep process teaching systems is easy to follow.
Correct -- This class contains very useful information related to civil engineering
Correct -- get all the help you can get outside of the class because the course is more difficult than most courses
Correct -- A real good course, free talk, deep thinking.
Correct -- I liked learning about concrete design because I believe that this is something I want to do in the future with my career.
Incorrect -- nones
Correct -- I highly recommend taking Dr. Nossoni, she is extremely helpful and you will learn a lot from her.
Correct -- they have good knowledge of the course
Incorrect -- the theoretical classes are boring and we can't focus the whole time – the course should be on campus better than being online –
the midterm exam was really hard and has complicated system and time is not enough to finish – project need much time to be
done open book for final exam is a good idea
Incorrect -- multiple choices
Correct -- I liked that the class was balanced between exercises and lectures, that definitely enhanced my learning.
Incorrect -- Assignments were very lengthy. No flexibility in coursework has been observed despite President's instructions.
Correct -- An example based class is a great way to teach someone something new, however it shouldnt be the sole point of the class.
Incorrect -- The PowerPoint presentations could be really boring.
Incorrect -- The dam tests. We never took a single test during class time. I understand that class time is limited, but if you want to hold the tests,
please do it during the actual class time. I had already made plans during couple of the test times months in advance and had to
cancel them because all of a sudden i now have a test. The HW grading system is also ridiculously hard. One simple mistake on the
HW may equal anywhere from 1 to ten points off the assignment, please be more reasonable.
Correct -- My advice for anyone who is taking this class I to take it seriously, this class is not a class to be joking around also ask questions to
Dr. Nossoni during the lectures or via groupme if you are confuse about something it will really help you when you are preparing for
exams. In addition, don't try cheating in this class because one you are embarrassing your dignity as a student and also braking the
trust with the professor. Do your homework because is beneficial.
Incorrect -- I would say to line up the homework, class topics and quizzes better so that they work with each other.
Correct -- Doing many in–class examples were very helpful in learning the material.
Correct -- practical learning
Incorrect -- It was difficult to learn the calculations online, but otherwise I have no suggestions.
Correct -- projects
Correct -- The teacher does a great job explaining what needs to be explained it is just a lot of materials to cover in one class
Correct -- If you looking for green and sustainable environment as a civil and environmental engineering students this is the course which make
you passionate towards your goal.
Correct -- This cource is too useful in construction industry and for environment as sustainable free
Correct -- I liked the PowerPoint lectures and in–class notes.
Incorrect -- Maybe don't announce people's grades to the whole class, that's rude.
Correct -- N/A–– Great work!!
Correct -- I really liked the way this class was taught. I liked the structure of the class, the material, and the enthusiasm of Dr. Nossoni. I am so
glad I chose her for this class, I never dreaded going nor did I hesitate to ask questions, it was actually fun to learn. People wanted
to learn, not because they had to learn. Dr. Nossoni is so smart and was able to answer any questions we had, and I value that
greatly when taking courses.
Correct -- Projects
Correct -- All the aspect of the course was sequenced will and described the topic will
Correct -- Some of the lab experiments were enjoyable to do when we were on campus together.
Incorrect -- This class was very hard. Tests were very hard and the homework was worth very little in the class.
Incorrect -- nothing
Correct -- Do the assignments, the extra credit, and be active in the class.
Incorrect -- The class itself was very jumbled making it hard to actually learn any of the content.
Correct -- To learn more in Sustainability, just be in attention in class
Correct -- Despite this class being pure online, (COVID – Restrictions and Already an online class to begin with) the professor did her best to
teach the material without knowing the students reactions.
Correct -- I liked how the instructor knew the material very well
Incorrect -- No suggestions.
Correct -- I like the subject matter
Incorrect -- Also, sometimes the lectures felt rushed and it was difficult to keep up writing things down and taking time to understand it.
Correct -- Actively listen during class when doing lectures and examples.
Correct -- I liked all the in–class problems. I appreciated the professor being available by group message outside of class.
Correct -- I definitely learned a lot. Professor Nossoni provides very good course notes.
Incorrect -- Don't test us on material we haven't learned in class. Make exams more like what would do on for homework and in–class problems.
Ease back on the amount of homework and quizzes. Be more thoughtful about student's mental health especially during the
quarantine.
Incorrect -- Practical
Incorrect -- The learning environment was not always positive. She quite often berated the class for the simplest of the things like yawning ( its a
9 am course, and most residential students wake up right before class), going to the dean about the test times or asking what she
considered a stupid question.
Incorrect -- I enjoyed having her as a professor but i was never personally affected by her schedule changes. I could see how other people might
not have been fond of her if her exams conflicted with their other activitics.
Incorrect -- I feel this class needs several improvements. The professor's attitude and demeanor during class time were incredibly negative. The
teacher seemed to constantly demand respect from the students but I did not seem to return that respect to her students. If someone
was not clear or we didn't understand the problem, we were questioned how we did not know this rather than being taught or
reminded. The professor constantly seemed to treat this class as the most important class in the entire curriculum and immediately
placed it on a pedsestal above all other classes. this was apparent when she schedule her exams outside of the set class time and
even asked students to try and miss other classes to take her exams after she discussed how important attendance to her class was.
It also did not seem like the teacher was concerned with the large number of students that were struggling with her class. The test
average were usually low and at times the average grade was failing but she did not seem borthered by this but saw this as our fault
rather than as a reason for concern. Several improvements have to be made to this course to make for a positive learning environment
rather than the incredibly negative envirment i experienced.
Correct -- Take Dr. Nossoni for this course, she is a wonderful profesor.
Correct -- she was very clear in her explanation
Correct -- Breakout room discussion face made me impressive and involved in class.
Correct -- I would suggest that the most difficult topics in the course, such as Geothermal energy, to be explained slower and more thoroughly.
Also, I would suggest to include teaching the use of Google Sketchup and Life Cycle Assessment software during class time.
Correct -- do the hw and use the book to supplement learning and help with homework
Incorrect -- Please slow down in class, it is impossible to keep up with your writing. Also, less homework, since each assignment took 5+ hours
to complete.
Incorrect -- Have to show up to class and do all the work
Incorrect -- Ask questions if confused
Incorrect -- Don't schedule tests outside of the class time.
Incorrect -- I would tell them to make sure their courseload is light enough so that they have time for this course.
Correct -- The teacher went out of her way to involve and reach out to all students.
Incorrect -- Make sure you understand everything, ask a lot of questions and it extremely likely that you won't get the grade that you expect since
the grades are solely based on exams.
Correct -- If you have a problem with the homework, contact the professor ASAP.
Incorrect -- I dont have any
Incorrect -- don't get frustrated when students, especially juniors don't understand
Incorrect -- More scooter paths across the classroom
Correct -- i feel that i learned well in this course
Correct -- Work hard, do the homework.
Correct -- Pay attention, follow the examples as close as possible, and study for all quizes.
Incorrect -- Lectures were fairly clear but tricky
Correct -- her method of teaching in class was highly effective
Correct -- Good class and instructor
Correct -- All design aspects are very important and like each and everyone aspect of this course. Regarding assignment and class practices
professor Goli is very organized and very clear in her way of testing and grading which makes us work more effective and honesty
Incorrect -- Be more clear on how things should be done. Outlining the steps for project three would have been helpful.
Incorrect -- do the homework
Incorrect -- I would not recommend to another student
Correct -- Take notes especially on the calculations part of the course.
Correct -- Green building
Correct -- I like the way things were repeated multiple times that helps very much. Go into detail alittle more otherwise great
Incorrect -- I got left behind some times when going over problem together as a glass.
Incorrect -- the example packet problems
Correct -- I really liked the way you explained the material, and broke each problem into simple to follow steps. As well as explain how you got
each equation that you used. Overall, I really enjoyed your class and wish I had room next semester to take advanced concrete with you.
Incorrect -- Its tough.
Correct -- Dr. nossoni was always well prepared for every class and her teaching is phenomenal
Correct -- the course was very organized and she always wanted to help
Correct -- I liked that the homework helped to enhance what we learned in class.
Incorrect -- go a little be slow on each topic.
Incorrect -- Be prepared to do a lot of work for this class. Be prepared to be confused with a few of the labs.
Incorrect -- before giving any work on software make sure students are aware of that software (google Sketchup)
Correct -- good luck.
Incorrect -- study for the exams.
Correct -- she made online very interactive and less boring
Incorrect -- Know basic math
Correct -- enjoyable to learn from.
Incorrect -- Reduce course work, spent much more time on this class than other Civil Engineering classes. With taking more than 4 classes, it
was very difficult to balance all other classes out with this one.
Incorrect -- Be prepared to spend an extreme amount of time working on this class just to end up failing in the end. Expect exams on designing
bridges when you're only taught how to design floor plans. Be prepared to have mental breakdowns after every test in this class. Be
prepared not to sleep. Just don't take this tech elective. Do open channel instead.
Correct -- Come to class and pay attention. That way you can pick up the minimum amount of what is expected to learn.
Correct -- The teacher was great, she was very energetic with the course, and always willing to talk about the topic or answer any question.
Correct -- Easy way out is the online section but its better to learn more for your money.
Incorrect -- The personability of the topics we covered was good. As well as being challenged intellectually
Correct -- Positive experience.
Correct -- Examples, Examples Examples. So useful for learning design.
Correct -- Be ready to learn about LEED. If you’re a competent engineering student, it’s really not difficult.
Incorrect -- it was too much work for only 2 credits
Incorrect -- Cutting down theory will help students to memorize the most important things.
Correct -- she went though a lot of examples
Correct -- it will be more effective for better understanding to design one entire project with all the related steps to be consider in completion